# Generated by Django 2.2 on 2020-05-05 09:11

import caching.base
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(default='')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=256)),
                ('img', imagefield.fields.ImageField(blank=True, height_field='img_height', null=True, upload_to='students', width_field='img_width')),
                ('img_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('img_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('img_ppoi', imagefield.fields.PPOIField(default='0.5x0.5', max_length=20)),
            ],
            options={
                'verbose_name': 'Teacher',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=256)),
                ('img', imagefield.fields.ImageField(blank=True, height_field='img_height', null=True, upload_to='students', width_field='img_width')),
                ('avg_mark', models.FloatField(default=5)),
                ('img_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('img_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('img_ppoi', imagefield.fields.PPOIField(default='0.5x0.5', max_length=20)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='front.ClassName')),
            ],
            options={
                'verbose_name': 'Student',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_check', models.DateTimeField(blank=True, null=True)),
                ('date_loading', models.DateTimeField(blank=True, null=True)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('mark_ai', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Не выполнено'), (1, 'На проверке'), (2, 'Проверенно'), (3, 'Просрочено')], default=0)),
                ('file_name', models.CharField(blank=True, max_length=256, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='solutions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='front.Student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='front.Task')),
            ],
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.AddField(
            model_name='classname',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='front.Teacher'),
        ),
    ]
